optics/views/ctq_views.py
from flask import Blueprint, render_template, request, url_for
from flask_sqlalchemy import model
from numpy.lib.function_base import append
import pandas as pd
from datetime import date, datetime, timedelta
from pandas.core.frame import DataFrame
from sqlalchemy.orm import query
from sqlalchemy.orm.session import Session
from werkzeug.utils import redirect, secure_filename
from optics import db
from optics.models import MFD, PMD, Chromatic, Coating, Common, Cutoff, DrawNumber, Geometry, Preform, User, OTDR
from datetime import datetime
import os
import sqlite3
import numpy as np
from .auth_views import login_required
sqlite3.register_adapter(np.int64, lambda val: int(val))
import copy

bp = Blueprint('ctq', __name__, url_prefix='/ctq')

@bp.route('/static_ctq')
@login_required
def go_ctq():
    itemsList = ['att1310ose', 'att1550ose', 'mfd1310ose', 'fiberCutoffOse', 'cladDiaOse', 'cladOvoOse',
                 'eccOSe', 'coat2Dia', 'coat1Dia', 'zwl', 'slope', 'disp1285', 'disp1290',
                 'disp1550', 'pmd']

    return render_template('ctq_trend.html', itemList = itemsList)

@bp.route('/trend_ctq', methods = ['POST'])
@login_required
def cal_ctq():
    day = request.form['date']
    item = request.form['item']

    queryset = db.session.query(Common.spoolID,Common.measure_date, Common.drawNumber,\
        OTDR.att1310ose, OTDR.att1550ose,\
        MFD.mfd1310ose, Cutoff.fiberCutoffOse, 
        Geometry.cladDiaOse, Geometry.cladOvoOse, Geometry.eccOse,\
        Coating.coat2Dia, Coating.coat1Dia,\
        Chromatic.zwl, Chromatic.slope,\
        Chromatic.disp1285, Chromatic.disp1290, Chromatic.disp1550,\
        PMD.pmd
        )\
        .filter(Common.measure_date>=datetime.strptime(day, '%Y-%m-%d') - timedelta(days=10))\
        .filter(Common.measure_date<=day)\
        .filter(Common.spoolID == OTDR.spoolID)\
        .filter(Common.spoolID == MFD.spoolID)\
        .filter(Common.spoolID == Cutoff.spoolID)\
        .filter(Common.spoolID == Geometry.spoolID)\
        .filter(Common.spoolID == Coating.spoolID)\
        .filter(Common.spoolID == Chromatic.spoolID)\
        .filter(Common.spoolID == PMD.spoolID)

    df = pd.read_sql_query(queryset.statement, queryset.session.bind)
    df = df[['measure_date', 'drawNumber', item]]
    df = df.replace(0, np.nan)

    date_range = (df['measure_date'].drop_duplicates()).sort_values()
    df = df.groupby(['drawNumber', 'measure_date']).mean()
    df = df.unstack()

    dates = []
    for i in range(0, date_range.shape[0]):
        dates.append((date_range.iloc[i]).strftime('%Y-%m-%d'))
    df.columns = dates
    df['tower'] = df.index
    #######################################################
    valueList = []
    valuesList_nonDraw = []
    for i in range(0, df.shape[0]):
        static_values = []
        static_values.append(df.iloc[i]['tower'])
        for date in range(0, len(dates)):
            static_values.append(round(df.iloc[i][date], 3))
        valueList.append(static_values)
    valuesList_nonDraw = copy.deepcopy(valueList)
    for i in range(0, len(valuesList_nonDraw)):
        valuesList_nonDraw[i].pop(0)

    return render_template('ctq_result.html', day = day, item = item, valueList = valueList, 
                           valuesList_nonDraw = valuesList_nonDraw, dates = dates)

optics/views/main_views.py
from flask import Blueprint, render_template, request, url_for, session, flash, g
import json
from flask.helpers import flash
from werkzeug.utils import redirect
from optics.models import User
from .auth_views import login_required
import random
import pandas as pd
from flask import Blueprint, render_template, request, url_for
from flask_sqlalchemy import model
import pandas as pd
from datetime import datetime
from pandas.core.frame import DataFrame
from sqlalchemy.orm import query
from sqlalchemy.orm.session import Session
from werkzeug.utils import redirect, secure_filename
from optics import db
from optics.models import MFD, OTDR, Chromatic, Coating, Common, Cutoff, DrawNumber, Geometry, PMD, MacroBending, NcrCode, Preform, Resin
import os
import sqlite3
import numpy as np
from .auth_views import login_required
sqlite3.register_adapter(np.int64, lambda val: int(val))


bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def log_in():
    return render_template('log_in.html')

@bp.route('/login', methods=('GET', 'POST'))
def home():
    if request.method == 'POST':
        error = None
        email = request.form['inputEmail']
        password = request.form['inputPassword']
        user = User.query.filter_by(userEmail=request.form['inputEmail']).first()
        #print(user.userEmail)
        if not user:
            error = "등록되지 않은 사용자 입니다"
        elif not password:
            error = "패스워드를 입력하세요"
        elif password != 'lsuser':
            error = "패스워드가 정확하지 않습니다"
        if error is None:
            session['user_id'] = user.id
            return redirect(url_for('main.re_home'))
        flash(error)
    return render_template('log_in.html')

@bp.route('/home')
@login_required
def re_home():
    return render_template('home.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.rehome'))

optics/views/ncr_views.py
from flask import Blueprint, render_template, request, url_for
from flask_sqlalchemy import model
import pandas as pd
from datetime import date, datetime
from pandas.core.frame import DataFrame
from sqlalchemy.orm import query
from sqlalchemy.orm.session import Session
from werkzeug.utils import redirect, secure_filename
from optics import db
from optics.models import MFD, PMD, Chromatic, Coating, Common, Cutoff, Geometry, NcrCode, Preform, Resin, User, OTDR, DrawNumber
from datetime import datetime
import os
import sqlite3
import numpy as np
sqlite3.register_adapter(np.int64, lambda val: int(val))
from sqlalchemy import or_
from .auth_views import login_required
bp = Blueprint('ncr', __name__, url_prefix='/ncr')

@bp.route('/draw')
@login_required
def go_draw():
    formList = Preform.query.all()
    preformList = ['None']
    for pre in formList:
        preformList.append(pre.preform)
    
    resins= Resin.query.all()
    resinList = ['None']
    for re in resins:
        resinList.append(re.resin)
        
    ncrs = NcrCode.query.all()
    ncrList = ['None']
    for n in ncrs:
        ncrList.append(n.code)

    return render_template('ncr_draw.html', preformList = preformList, resinList = resinList,\
        ncrList = ncrList)

@bp.route('/draw_result', methods = ['POST'])
@login_required
def cal_draw():
    start = request.form['start_date']
    stop = request.form['stop_date']
    preform = request.form['preform']
    resin = request.form['resin']
    ncr = request.form['ncr']

    drawList = DrawNumber.query.all()
    dList = []
    for draw in drawList:
        dList.append(draw.drawNumber)

    queryset_total = db.session.query(Common.spoolID,Common.measure_date, Common.com, OTDR.length,\
        Common.drawNumber, Common.resin)\
        .filter(Common.measure_date>=start)\
        .filter(Common.measure_date<=stop)\
        .filter(Common.spoolID == OTDR.spoolID)\
        .filter(Common.com == preform)\
        .filter(Common.resin == resin)
    df_total = pd.read_sql_query(queryset_total.statement, queryset_total.session.bind)
    df_total = df_total[['drawNumber', 'length']]

    df_total = df_total.groupby(['drawNumber']).sum()
    df_total.unstack()
    df_total['drawT'] = df_total.index

    TotalDic = {}
    for i in range(0, df_total.shape[0]):
        if df_total.iloc[i]['length']:
            TotalDic[df_total.iloc[i]['drawT']] = df_total.iloc[i]['length']

    queryset_part = db.session.query(Common.spoolID,Common.measure_date, Common.com, OTDR.length,\
        Common.drawNumber, Common.resin)\
        .filter(Common.measure_date>=start)\
        .filter(Common.measure_date<=stop)\
        .filter(Common.spoolID == OTDR.spoolID)\
        .filter(Common.com == preform)\
        .filter(Common.resin == resin)\
        .filter(or_(Common.ncrCode1 == ncr , Common.ncrCode2 == ncr , Common.ncrCode3 == ncr ))
    df_part = pd.read_sql_query(queryset_part.statement, queryset_part.session.bind)
    df_part = df_part[['drawNumber', 'length']]

    df_part = df_part.groupby(['drawNumber']).sum()
    df_part.unstack()
    df_part['drawT'] = df_part.index

    PartDic = {}
    for i in range(0, df_part.shape[0]):
        if df_part.iloc[i]['length']:
            PartDic[df_part.iloc[i]['drawT']] = df_part.iloc[i]['length']

    labels = []
    values = []
    for key, value in TotalDic.items():
        if key in PartDic:
            labels.append(key)
            values.append(PartDic[key] / value *100)
        else:
            labels.append(key)
            values.append(0.00)

    return render_template('ncrDraw_result.html', labels = labels, values = values, ncr = ncr, start=start, stop=stop, resin=resin, preform=preform)

optics/views/packing_views.py
from flask import Blueprint, render_template, request, url_for, session, flash, g
import json
from flask.helpers import flash
from werkzeug.utils import redirect
from optics.models import Packing
from .auth_views import login_required
from optics import db
import pandas as pd

bp = Blueprint('packing', __name__, url_prefix='/packing')

@bp.route('/packing_update')
@login_required
def update():
    packing_list = []
    query_set = db.session.query(Packing.customerName, Packing.orderLength, Packing.packedLength, Packing.packedSpoolCount, Packing.stdLength)
    df = pd.read_sql_query(query_set.statement, query_set.session.bind)
    df['percent'] = df['packedLength'] / df['orderLength'] *100
    rows = df.shape[0]
    for row in range(0, rows):
        packing_list.append(df.iloc[row].to_list())
    return render_template('packing.html', packing_list=packing_list)

optics/views/user_views.py
from flask import Blueprint, render_template, request, url_for
from flask_sqlalchemy import model
import pandas as pd
from datetime import datetime
from pandas.core.frame import DataFrame
from sqlalchemy.orm import query
from sqlalchemy.orm.session import Session
from werkzeug.utils import redirect, secure_filename
from optics import db
from optics.models import User 
import os
import sqlite3
import numpy as np
from .auth_views import login_required
sqlite3.register_adapter(np.int64, lambda val: int(val))

bp = Blueprint('user', __name__, url_prefix='/user')

@bp.route('/registrate')
@login_required
def registrate():
    return render_template('user_registration.html')

@bp.route('/registration', methods=['POST'])
@login_required
def registration():
    if request.form['email']:
        query_user = User(create_date = datetime.now(),
                        userEmail = str(request.form['email'])
                )
        db.session.add(query_user)
        db.session.commit()
        
    return '사용자 등록 완료...'

optics/templates/bending_intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>머신러닝</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='chart.min.js') }}"></script>
    <style>
        .content{
            display: flex;
            justify-content:space-evenly;
            align-content: center;
            padding: 10px;
        }
        .card{
            width: 400px;
            height: 350px;
        }
        .img-box{
            width: 400px;
            height: 250px;
        }
        .row1{
            display: flex;
            justify-content: space-around;
            margin-bottom: 50px;
            margin-left: 120px;
            margin-right: 120px;
        }
        .row2{
            display: flex;
            justify-content: space-around;
            margin-bottom: 50px;
            margin-left: 120px;
            margin-right: 120px;
        }
        img{
            padding: 20px;
        }
        .input{
            display: flex;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <h3 style="margin-left: 100px; padding: 10px; color: gray; margin-top: 20px;">광섬유 굴곡손실 특성 예측 모델</h3>
    <h5 style="margin-left: 100px; padding: 10px; color: gray">검사, 제조, 원자재 데이터 기반의 모델링 결과로 광학특성을 예측합니다.</h5>
    <div class="totoal-container">
        <div class="row1">
        <div class="container-box">
            <div class="card">
                <div class="img-box">
                <img src="{{ url_for('static', filename='images/roc_plot.png') }}" width="400px" height="250" class="card-img-top" alt="...">
                </div>
                <div class="card-body">
                    <h5 class="card-title">LightGBM 알고리즘</h5>
                    <p class="card-text">Tree 모델로 회귀모델을 구현합니다.</p>
                </div>
            </div>
        </div>

        <div class="container-box">
            <div class="card">
                <div class="img-box">
                <img src="{{ url_for('static', filename='images/threshold_plot.png') }}" width="400px" height="250" class="card-img-top" alt="...">
                </div>
                <div class="card-body">
                    <h5 class="card-title">LightGBM 알고리즘</h5>
                    <p class="card-text">Tree 모델로 회귀모델을 구현합니다.</p>
                </div>
            </div>
        </div>
        </div>
        <div class="row2">
        <div class="container-box">
            <div class="card">
                <div class="img-box">
                    <form action="{{ url_for('machineLearning.upload_bending') }}" method="POST" enctype="multipart/form-data">
                    <div class="input">
                        <div class="in">
                        <input class="form-control" type="file" name="csv_name">
                        </div>
                        <div class="in">
                        <input type="submit" class="btn btn-dark" id="btn" onclick="loading();" value="예측 실행">
                        </div>
                    </div>
                    <div class="predict-table" style="width: 100%; height: 250px; overflow: auto;">
                        <table class="table table-bordered">
                            <thead>
                                <tr class="thead-dark">
                                    <th>꼬리표 번호</th>
                                    <th>예측 굴곡손실[Pass or Fail]</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if spoolID %}
                                {% for i in range(0, 20) %}
                                    <tr>
                                        <td>{{ spoolID[i] }}</td>
                                        <td>{{ y_pred[i] }}</td>
                                    </tr>
                                {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                    </form>
                </div>
                <div class="card-body">
                    
                </div>
            </div>
        </div>
        <div class="container-box">
            <div class="card">
                <div class="img-box">
                <img src="{{ url_for('static', filename='images/importance_bending.png') }}" class="card-img-top" alt="...">
                </div>
                <div class="card-body">
                    <h5 class="card-title">LightGBM 알고리즘</h5>
                    <p class="card-text">Tree 모델로 회귀모델을 구현합니다.</p>
                </div>
            </div>
        </div>
        </div>
    </div>


</body>
</html>

optics/templates/ctq_trend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CTQ 조회</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!--<script src="{{ url_for('static', filename='chart.min.js') }}"></script>-->
    <style>
        h1{
            margin-top: 20px;
            margin-left: 20px;
        }
        h3{
            margin-left: 20px;
            margin-top: 15px;
        }
        .my-form{
            margin-left: 20px;
            margin-top: 15px;
        }
        .info{
            margin-top: 15px;
        }
        .part{
            display: flex;
            justify-content: space-between;
        }
        .character-table{
            margin-top: 30px;
            margin-right: 150px;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <h3 style="color: gray;margin-top: 30px;">일일 단위로 CTQ 특성에 대한 평균 데이터를 제공합니다.</h3>
    <h5 style="color: gray;margin-left: 20px;margin-top: 20px;">입력날짜를 기준으로 최근 10일 간의 결과를 제공합니다.</h5>

    <div class="part">
        <div class="my-form">
            <form action="{{ url_for('ctq.cal_ctq') }}" method="POST">
                <div class="info">
                    <label>조회 기준일자</label>
                    <input type="date" class="form-control" name="date" id="today">
                </div>
                    <div class="info">
                        <label>광학특성</label>
                    {% if itemList %}
                        <select class="form-select" name="item" style="font-size: 17px;">
                            {% for item in itemList %}
                                <option value="{{ item }}">{{ item }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                <div class="info">
                    <input class="btn btn-dark" type="submit" value="조 회" style="width: 240px;">
                </div>
            </form>
        </div>
        <div class="character-table">
            <h5 style="margin: 0px 20px 20px 20px;">광학특성 조회 코드</h5>
            <div class="container" style="width: 500px;">
                <table class="table table-striped">
                    <thead>
                        <tr class="thead-dark">
                            <th>광학 특성</th>
                            <th>조회 코드</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1310nm 광손실</td>
                            <td>att1310ose</td>
                        </tr>
                        <tr>
                            <td>1550nm 광손실</td>
                            <td>att1550ose</td>
                        </tr>
                        <tr>
                            <td>MFD</td>
                            <td>mfd1310ose</td>
                        </tr>
                        <tr>
                            <td>차단파장</td>
                            <td>fiberCutoffOse</td>
                        </tr>
                        
                        <tr>
                            <td>클래드외경</td>
                            <td>cladDiaOse</td>
                        </tr>
                        <tr>
                            <td>클래드비원율</td>
                            <td>cladOvoOse</td>
                        </tr>
                        <tr>
                            <td>ECC</td>
                            <td>eccOse</td>
                        </tr>

                        <tr>
                            <td>코팅외경 2차</td>
                            <td>coat2Dia</td>
                        </tr>

                        <tr>
                            <td>코팅외경 1차</td>
                            <td>coat1Dia</td>
                        </tr>

                        <tr>
                            <td>영분산 파장</td>
                            <td>zwl</td>
                        </tr>

                        <tr>
                            <td>기울기</td>
                            <td>slope</td>
                        </tr>

                        <tr>
                            <td>색분산 계수 1285nm</td>
                            <td>disp1285</td>
                        </tr>

                        <tr>
                            <td>색분산 계수 1290nm</td>
                            <td>disp1290</td>
                        </tr>

                        <tr>
                            <td>색분산 계수 1550nm</td>
                            <td>disp1550</td>
                        </tr>

                        <tr>
                            <td>PMD</td>
                            <td>pmd</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script>
        let today = new Date();
        document.getElementById("today").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);
    </script>
</body>
</html>

optics/templates/log_in.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>OptSys</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/signin.css') }}">
    {%with messages = get_flashed_messages()%}
    {%if messages %}
      <script type="text/javascript">
        alert("{{messages[-1]}}");
      </script>
      {%endif%}
    {%endwith%}
  </head>

  <body class="text-center">
    
    <form class="form-signin" action="{{url_for('main.home')}}" method="post">
 
      <img class="mb-4" src="{{ url_for('static', filename='images/company-logo.svg') }}" alt="" width="72" height="72">

      <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="Email address" required autofocus>

      <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Password" required>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me">E-mail 저장 
        </label>
      </div>

      <button class="btn btn-lg btn-primary btn-block" type="submit" >로그인</button>

      <p class="mt-5 mb-3 text-muted">&copy; LS전선 통신사업부/광섬유 측정실</p>
    
    </form>

    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

  </body>

</html>

optics/templates/migration_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data migration 완료</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='chart.min.js') }}"></script>-->
</head>
<body>
        {% include 'navbar.html' %}
        <h3>마이그레이션이 완료되었습니다...</h3>
    <!--<script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>-->
</body>
</html>

optics/templates/ncr_draw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Draw NCR</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='chart.min.js') }}"></script>
    <style>
        h3{
            margin: 50px;
        }
        .total{
            display: flex;
            justify-content: space-around;
            margin: 30px;
        }
        h5{
            margin: 20px;
        }
        .date{
            display: flex;
            justify-content: space-around;
        }
        .search-date{
            margin: 0px 70px 20px 0px;
        }
        .info{
            margin: 20px 0px 20px 0px;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <br>
    <h3 style="color: grey;">Draw 공정의 이상내역을 조회합니다.</h3>
    <div class="total">
        <div class="part1">
            <h5>조회 정보</h5>
            <form action="{{ url_for('ncr.cal_draw') }}" method="POST">
                <div class="info">
                <div class="date">
                    <div class="search-date form-style">
                        <label>조회 시작일</label>
                        <input type="date" class="form-control" name="start_date" id="today_start">


                    </div>
                    <div class="search-date form-style">
                        <label>조회 종료일</label>
                        <input type="date" class="form-control" name="stop_date" id="today_stop">
                    </div>

                </div>
                </div>

                
                <div class="info">
                    <label>프리폼</label>
                        {% if preformList %}
                            <select class="form-select" name="preform" style="font-size: 17px;">
                                {% for preform in preformList %}
                                    {% if preform != 'None' %}
                                    {% if preform == 'AW' %}
                                    <option selected="selected" value="{{ preform }}">{{ preform }}</option>
                                    {% else %}
                                    <option value="{{ preform }}">{{ preform }}</option>
                                    {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </select>
                        {% endif %}
                </div>
                <div class="info">
                    <label>레진</label>
                    {% if resinList %}
                        <select class="form-select" name="resin" style="font-size: 17px;">
                            {% for resin in resinList %}
                                {% if resin != 'None' %}
                                {% if resin == 'V' %}
                                <option selected="selected" value="{{ resin }}">{{ resin }}</option>
                                {% else %}
                                <option value="{{ resin }}">{{ resin }}</option>
                                {% endif %}
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                <div class="info">
                    <label>이상코드</label>
                    {% if ncrList %}
                        <select class="form-select" name="ncr" style="font-size: 17px;">
                            {% for ncr in ncrList %}
                                {% if ncr != 'None' %}
                                {% if ncr == 'G1' %}
                                <option selected="selected" value="{{ ncr }}">{{ ncr }}</option>
                                {% else %}
                                <option value="{{ ncr }}">{{ ncr }}</option>
                                {% endif %}
                                {% endif %}
                            {% endfor %}
                        </select>
                    {% endif %}
                </div>
                <input class="btn btn-dark" type="submit" value="조 회">
            </form>
        </div>
        <div class="part2">
            <h5>이상내역 코드</h5>
            <div class="container" style="width: 500px;">
                <table class="table table-striped">
                    <thead>
                        <tr class="thead-dark">
                            <th>이상내역</th>
                            <th>조회 코드</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>G1</td>
                            <td>양파장 단차</td>
                        </tr>
                        <tr>
                            <td>G2</td>
                            <td>단차</td>
                        </tr>
                        <tr>
                            <td>G3</td>
                            <td>단차</td>
                        </tr>
                        <tr>
                            <td>G4</td>
                            <td>버블</td>
                        </tr>
    
                        <tr>
                            <td>G5</td>
                            <td>휨</td>
                        </tr>
    
                        <tr>
                            <td>O7</td>
                            <td>차단파장</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
    <script>
        let today = new Date();
        document.getElementById("today_start").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);
        document.getElementById("today_stop").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);
    </script>
</body>
</html>

optics/templates/user_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>사용자 등록</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='chart.min.js') }}"></script>-->
    <style>
        .form-items{
            width: 25%;
            display: flex;
            justify-content: space-between;
            margin-left: 50px;
        }
    </style>
</head>
<body>
        {% include 'navbar.html' %}
        <h3 style="color: gray; margin-top: 30px; margin-left: 50px;">신규 사용자 등록을 진행합니다</h3>
        <p style="color: gray; margin-left: 50px">사용자의 e-mail 주소를 입력하세요</p>
        <form action="{{ url_for('user.registration') }}" method="POST">
            <div class="form-items">
                <div>
            <input type="email" class="form-control" name="email" placeholder="e-mail 주소">
            </div>
            <div>
            <input type="submit" class="btn btn-dark" value="사용자 등록">
            </div>
            </div>
        </form>   
    <!--<script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>-->
</body>
</html>